image: archlinux:latest

pages:
  stage: deploy
  script:
    - pacman -Syu --noconfirm kotlin
    - ./scripts/ci.main.kts --highlight "Kirchenführung" --targetDir "public" --targetUrl "https://kirchewds.gitlab.io/kirchenfuehrung-data/"
  artifacts:
    paths:
      - public
    expire_in: 2 days
  only:
    - master
